### ISSUE TITLE
Are there any plans to make the extension configurable?

### ISSUE THREAD

**Issue by barow** [froemken/repair_translation#12]
It's rather a missing feature than an issue of course:

Are there any plans to add options for configuring the extension?
Once installed there are always the translations displayed, no matter how the language configuration of a single page is. 

What I would appreciate is the possibility to determine (via TS) if the translation or the default record is being displayed in one case (or one page) or another.

Best, 
barow

**Comment by froemken** [comment]
I hope that this extension will never be configureable. The extension should read all configuration from TS, page properties and Installtool ans should react as expected. It's up to the extension developers to show the radioboxes, where you can decide if original or translated records should be shown.

**Comment by froemken** [comment]
It's up to the extension developer to add addLanguageSynchronization to TCA

https://forge.typo3.org/issues/79658

My ext will not be configurable in future

Stefan
