### ISSUE TITLE
TYPO3 v9 compatibility

### ISSUE THREAD

**Issue by ckrrtp** [froemken/repair_translation#13]
Currently the extension does not seem to work in TYPO3 v9 yet. Are there already plans here?

**Comment by froemken** [comment]
I currently don't know if the language problem is still valid in TYPO3 9. So, if yes, I'm sure there will be a new version.

**Comment by froemken** [comment]
Cool...there is a big patch pending in TYPO3 9: https://review.typo3.org/#/c/53974/
If it will made it into TYPO3 9, repair_translation will not be needed anymore.
