### ISSUE TITLE
Tag release 1.4.1

### ISSUE THREAD

**Issue by jrenggli** [froemken/repair_translation#19]
Hi

Could you please tag version 1.4.1 released on May 20, 2019.
Currently this one is only available in TER https://extensions.typo3.org/extension/repair_translation/.

Personally I prefer using the composer package directly from https://packagist.org/packages/stefanfroemken/repair_translation

**Comment by froemken** [comment]
Hello @jrenggli 

I have just pushed version 1.4.1 to composer.
Thank you for that hint

Stefan
