### ISSUE TITLE
Workspaces und Übersetzung

### ISSUE THREAD

**Issue by bauermar** [froemken/repair_translation#2]
Hey Stefan,

ich habe noch einen Fehler gefunden. Wenn man sich im WS befindet und dann bei der Übersetzung eines Datensatzes ein bisher schon bestehendes Bild löscht (im Live schon übersetzt) und dann ein neues einfügt verschwindet das "Live" Bild nicht sondern wird weiterhin im BE und FE (WS) angezeigt. Ich hatte leider noch keine Zeit mir das Problem selbst anzuschauen aber wäre cool wenn du das auch noch in deine repair Extension einbauen könntest :)

Viele Grüße
Marc

**Comment by bauermar** [comment]
Der folgende Code löst das Problem im Frontend:

// getNewlyCreatedTranslatedSysFileReferences()
<pre>
if (empty($rows)) {
	$rows = array();
}

foreach ($rows as $key=>&$row) {
	BackendUtility::workspaceOL('sys_file_reference', $row);
	if($row['t3ver_state'] == '2') {
		unset($rows[$key]);
	}
}
</pre>

**Comment by froemken** [comment]
Thank you for your help. I have just uploaded your code snippet into current master
