### ISSUE TITLE
News Bilder Sortierung

### ISSUE THREAD

**Issue by denweng** [froemken/repair_translation#3]
Die Sortierreihenfolge bei tx_news Bildern unterscheidet sich zwischen der Originalsprache und der Übersetzung, auch wenn diese in den Datensätzen gleich ist.
Wahrscheinlich wird in getNewlyCreatedTranslatedSysFileReferences in Repair.php im SQL Query die Sortierung von sys_file_reference.sorting_foreign nicht beachtet.

Viele Grüße
Tobias

**Comment by froemken** [comment]
Hi Gerald,

Patch schaut sinnvoll aus. Hab ihn soeben gemerged. Danke Dir

Stefan
