### ISSUE TITLE
mergeIfNotBlank has been removed in 8.6+ without replacement

### ISSUE THREAD

**Issue by kvonspiczak** [froemken/repair_translation#7]
Hey, just wanted to point out that: 
> The setting `mergeIfNotBlank` has been removed without replacement from the list of possible values of the TCA column property `l10n_mode`.

See: 

- [https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.6/Breaking-79243-RemoveL10n_modeMergeIfNotBlank.html](1)
- [https://github.com/froemken/repair_translation/blob/master/Classes/SignalSlot/Repair.php#L85](2)

**Comment by froemken** [comment]
Thank you @kvonspiczak 

it has been replaced with two radio buttons where the customer can choose between "custom" and "use default language".
I have just uploaded a new version to master and tag 1.3.0

Thank you for reporting this hint

Stefan
