### ISSUE TITLE
Provide extension on Packagist

### ISSUE THREAD

**Issue by martinhummer** [froemken/repair_translation#8]
Is there a possibility to provide this extension via packagist, so one could install it via composer?

**Comment by jdreesen** [comment]
As long as it is not on packagist you can add this to the `repositories` section in your `composer.json`:

```json
{
   "type": "vcs",
   "url": "https://github.com/froemken/repair_translation"
}
```

Then do `composer require stefanfroemken/repair_translation`, like you normally do.

**Comment by froemken** [comment]
Oh yes. Good point. Done

**Comment by martinhummer** [comment]
Perfect!
Thank you both.
